### ISSUE TITLE
实验8，缺了sys.h的修改内容，会导致segmentation fault

### ISSUE THREAD

**Issue by Erwwyh** [only9464/Operating-System-Experiment#2]
6. 实验8地址映射和内存共享-任务1

缺少对于/include/linux/sys.h的修改

![{第一处}](https://github.com/user-attachments/assets/f4bb32b7-7868-4704-888e-2ef1a5ea1bb1)
![{第二处}](https://github.com/user-attachments/assets/450dfb44-ab3f-4449-a02c-07df8ee564ac)

关于os坐牢坐了半节课这档子事，我可怜的信赖啊

**Comment by only9464** [comment]
感谢补充~！已经修改啦~~~hh（辛苦你坐牢了(）
