### ISSUE TITLE
Err: 实验八loop.c 变量i位置问题

### ISSUE THREAD

**Issue by Erwwyh** [only9464/Operating-System-Experiment#3]
根据实验指导书，i应该被创建在程序全局变量处，而非主函数栈区
![{指导书程序源码}](https://github.com/user-attachments/assets/c76e8308-2d24-4472-8483-56fc2a2f7b0c)

经验证，创建于主函数栈区的变量无法完全复现实验指导书的i变量地址位置

哥们你做的时候是硬算么……我都怀疑人生了

**Comment by only9464** [comment]
感谢指正！（copy得草率了（bushi））

**Comment by only9464** [comment]
修正：#4
