### ISSUE TITLE
实验八：地址映射与内存共享

### ISSUE THREAD

**Issue by penguinway** [only9464/Operating-System-Experiment#4]
对于 #3，按照实验文档要求，第一步调试全局变量时i的定义应该定义在全局变量处，但是第二步调试局部变量时，代码应该放在主函数栈区，故而提交作业时，i的定义是否应该仍在主函数栈区？如下图

![image](https://github.com/user-attachments/assets/29d15ad3-0f17-4cdd-bdb8-8927c15c6490)

**Comment by only9464** [comment]
你说的对，man！年代久远导致都忘了这个是改了位置运行两次的，你说的这个就是提交作业的时候的代码

**Comment by penguinway** [comment]
man, hahaha, what can i say

**Comment by only9464** [comment]
> man, hahaha, what can i say

maomao！
